Dedukti Set Param "encoding_file" "Coq".
Dedukti Set Param "syntax" "Dedukti".
Dedukti Set Param "Sort" "Sort".
Dedukti Set Param "Univ" "Univ".
Dedukti Set Param "Term" "Term".
Dedukti Set Param "sup" "sup".
Dedukti Set Param "univ" "univ".
Dedukti Set Param "prod" "prod".
Dedukti Set Param "cast" "cast".
Dedukti Set Param "use_cast" "true".
Dedukti Set Param "pred_univ" "true".
Dedukti Set Param "pred_prod" "true".
Dedukti Set Param "pred_cast" "true".
Dedukti Set Param "eps" "eps".
Dedukti Set Param "Cumul" "Cumul".
Dedukti Set Param "I" "I".
Dedukti Set Param "priv_univ" "true".
Dedukti Set Param "priv_prod" "true".
Dedukti Set Param "priv_cast" "true".
Dedukti Set Param "_univ" "univ'".
Dedukti Set Param "_prod" "prod'".
Dedukti Set Param "_cast" "cast'".
Dedukti Set Param "lifted_type_pattern" "cast".
Dedukti Set Param "prop" "prop".
Dedukti Set Param "type" "type".
Dedukti Set Param "set" "set".
Dedukti Set Param "type0" "type0".
Dedukti Set Param "Lvl" "Nat".
Dedukti Set Param "lvl0" "z".
Dedukti Set Param "lvlS" "s".
Dedukti Set Param "lvlMax" "max".
Dedukti Set Param "axiom" "axiom".
Dedukti Set Param "rule" "rule".
Dedukti Set Param "inlined_fixpoint" "true".
Dedukti Set Param "fix_arity_sort" "false".
Dedukti Set Param "0" "0".
Dedukti Set Param "S" "_S".
Dedukti Set Param "SA" "SA".
Dedukti Set Param "MA" "make_MA".
Dedukti Set Param "fix" "fix".
Dedukti Set Param "fix_proj" "fix_proj".
Dedukti Set Param "fix_oneline" "fixproj".
Dedukti Set Param "guard" "guarded?".
Dedukti Set Param "guarded" "guarded".
Dedukti Set Param "tpolymorphism" "true".
Dedukti Set Param "tpoly_cons"    "true".
Dedukti Set Param "named_univ"    "true".
Dedukti Set Param "universe_file" "U".
Dedukti Set Param "encoding_name" "template_cic".
Dedukti Set Param "encoding_file" "C".
